var searchData=
[
  ['case_20regressions_0',['Edge Case Regressions',['../md_test__expressions_2reference__output_2index.html#autotoc_md165',1,'']]],
  ['cases_20and_20edge_20cases_1',['Special Cases and Edge Cases',['../md_test__expressions_2reference__output_2index.html#autotoc_md164',1,'']]],
  ['catch2_20macros_2',['Key Catch2 Macros',['..//home/runner/work/bdd_test/bdd_test/tests/README.md#autotoc_md258',1,'']]],
  ['changes_3',['Submitting Changes',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md7',1,'']]],
  ['check_5fpython_5fversion_4',['check_python_version',['../namespacesetup__python__bdd.html#ac20bdc4c18fcc8b5a79d66e08542ed4d',1,'setup_python_bdd']]],
  ['checklist_5',['Pull Request Checklist',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md9',1,'']]],
  ['child_6',['child',['../structdag__walker_1_1_edge_info.html#ac9596643185b429fb3ec5ac4df06cf66',1,'dag_walker::EdgeInfo']]],
  ['child_5findex_7',['child_index',['../structdag__walker_1_1_edge_info.html#a73a4418ff838078b8bb8e65adf6c1b5f',1,'dag_walker::EdgeInfo']]],
  ['children_8',['children',['../structcudd__view.html#afe4cf5f004b3cd533b069e670ff844d1',1,'cudd_view::children()'],['../structexpression__view.html#a526bed245243dc5269ae3fce47fd13b0',1,'expression_view::children()'],['../structteddy__view.html#a487c7461b906cd91a02756a4daa7565e',1,'teddy_view::children()']]],
  ['childrenrange_9',['ChildrenRange',['../concept_children_range.html',1,'']]],
  ['class_5fdefinitions_10',['class_definitions',['../structmermaid__graph_1_1_mermaid_config.html#a2fd5e11db35b510ee0fb56a53043eb4d',1,'mermaid_graph::MermaidConfig']]],
  ['cli_11',['3. GitHub CLI',['../md_documentation_2dependency-management.html#autotoc_md45',1,'']]],
  ['cmake_20dependency_20management_12',['CMake Dependency Management',['../md_documentation_2dependency-management.html',1,'']]],
  ['cmake_20integration_13',['cmake integration',['../index.html#autotoc_md60',1,'3. Enable CMake Integration'],['..//home/runner/work/bdd_test/bdd_test/README.md#autotoc_md85',1,'CMake Integration']]],
  ['code_20contributions_14',['Code Contributions',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md13',1,'']]],
  ['code_20of_20conduct_15',['Code of Conduct',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md4',1,'']]],
  ['collect_5fnodes_5fand_5fedges_5ftopological_16',['collect_nodes_and_edges_topological',['../dag__walker_8hpp.html#aa5b986a5af0e7a7c0eea4dd354311332',1,'dag_walker']]],
  ['collect_5fvariables_5fwith_5fdag_5fwalker_17',['collect_variables_with_dag_walker',['../expression__graph_8hpp.html#a5535869a6b9cff09aae6d0ae8e1a1698',1,'collect_variables_with_dag_walker(const my_expression &amp;expr, std::unordered_set&lt; std::string &gt; &amp;variables):&#160;expression_graph.cpp'],['../expression__graph_8cpp.html#a5535869a6b9cff09aae6d0ae8e1a1698',1,'collect_variables_with_dag_walker(const my_expression &amp;expr, std::unordered_set&lt; std::string &gt; &amp;variables):&#160;expression_graph.cpp']]],
  ['compare_20all_20three_20implementations_18',['Compare All Three Implementations',['../index.html#autotoc_md66',1,'']]],
  ['comparison_20tool_19',['Python BDD Comparison Tool',['..//home/runner/work/bdd_test/bdd_test/README.md#autotoc_md83',1,'']]],
  ['complex_20logical_20operations_20',['Complex Logical Operations',['../md_test__expressions_2reference__output_2index.html#autotoc_md163',1,'']]],
  ['conduct_21',['Code of Conduct',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md4',1,'']]],
  ['configuration_22',['Build Configuration',['..//home/runner/work/bdd_test/bdd_test/tests/README.md#autotoc_md250',1,'']]],
  ['considerations_23',['Performance Considerations',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md17',1,'']]],
  ['console_20display_24',['1. Console Display',['../md_docs__index.html#autotoc_md29',1,'']]],
  ['consume_5ftoken_25',['consume_token',['../classbdd__demo__python_1_1_expression_parser.html#a1c956c1fb553b6e913956580cdc0cba8',1,'bdd_demo_python::ExpressionParser']]],
  ['continuous_20integration_26',['Continuous Integration',['..//home/runner/work/bdd_test/bdd_test/tests/README.md#autotoc_md272',1,'']]],
  ['contributing_27',['Contributing',['..//home/runner/work/bdd_test/bdd_test/README.md#autotoc_md89',1,'']]],
  ['contributing_20to_20bdd_20expression_20converter_28',['Contributing to BDD Expression Converter',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html',1,'']]],
  ['contributions_29',['contributions',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md13',1,'Code Contributions'],['../md__c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md10',1,'Types of Contributions']]],
  ['convert_5fto_5fbdd_30',['convert_to_bdd',['../teddy__convert_8hpp.html#af9f414b45190db6ccdd1232463f617f4',1,'teddy_convert.hpp']]],
  ['convert_5fto_5fbdd_5fwith_5fteddy_5fadapter_31',['convert_to_bdd_with_teddy_adapter',['../teddy__convert_8hpp.html#a795be9df121704cd1e7801ad7964641e',1,'teddy_convert.hpp']]],
  ['convert_5fto_5fcudd_5fbdd_32',['convert_to_cudd_bdd',['../cudd__convert_8hpp.html#a89729d1c0603a8012786f579e883389d',1,'cudd_convert.hpp']]],
  ['converter_33',['Contributing to BDD Expression Converter',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html',1,'']]],
  ['converter_20documentation_34',['BDD Expression Converter Documentation',['../md_docs__index.html',1,'']]],
  ['core_20functionality_35',['Core Functionality',['..//home/runner/work/bdd_test/bdd_test/README.md#autotoc_md72',1,'']]],
  ['count_5fnodes_5ftopological_36',['count_nodes_topological',['../dag__walker_8hpp.html#a016448d758a8f5a5977dc4640657555d',1,'dag_walker']]],
  ['coverage_20analysis_37',['Coverage Analysis',['..//home/runner/work/bdd_test/bdd_test/tests/README.md#autotoc_md271',1,'']]],
  ['create_5fvariable_5fordering_38',['create_variable_ordering',['../classbdd__demo__python_1_1_python_b_d_d_demo.html#a0fdbe5e84781104123c415a16d9b1d4d',1,'bdd_demo_python::PythonBDDDemo']]],
  ['cross_20library_20validation_39',['🔄 Cross-Library Validation',['../md_test__expressions_2reference__output_2index.html#autotoc_md160',1,'']]],
  ['cross_20library_20validation_20strong_40',['🔬 &lt;strong&gt;Cross-Library Validation&lt;/strong&gt;',['../index.html#autotoc_md62',1,'']]],
  ['ctest_20recommended_41',['Method 1: Using CTest (Recommended)',['..//home/runner/work/bdd_test/bdd_test/tests/README.md#autotoc_md253',1,'']]],
  ['cudd_20fixes_42',['Validate CUDD Fixes',['../index.html#autotoc_md67',1,'']]],
  ['cudd_5fconvert_2ehpp_43',['cudd_convert.hpp',['../cudd__convert_8hpp.html',1,'']]],
  ['cudd_5fgraph_2ecpp_44',['cudd_graph.cpp',['../cudd__graph_8cpp.html',1,'']]],
  ['cudd_5fgraph_2ehpp_45',['cudd_graph.hpp',['../cudd__graph_8hpp.html',1,'']]],
  ['cudd_5fiterator_46',['cudd_iterator',['../classcudd__iterator.html#a1f4bcb79fc50c1bee91f816513c2048e',1,'cudd_iterator::cudd_iterator()'],['../classcudd__iterator.html',1,'cudd_iterator']]],
  ['cudd_5fiterator_2ehpp_47',['cudd_iterator.hpp',['../cudd__iterator_8hpp.html',1,'']]],
  ['cudd_5fview_48',['cudd_view',['../structcudd__view.html',1,'']]],
  ['cudd_5fview_2ehpp_49',['cudd_view.hpp',['../cudd__view_8hpp.html',1,'']]],
  ['current_20dependencies_50',['Current Dependencies',['../md_documentation_2dependency-management.html#autotoc_md35',1,'']]],
  ['current_20test_20status_51',['Current Test Status',['..//home/runner/work/bdd_test/bdd_test/tests/README.md#autotoc_md265',1,'']]],
  ['current_5ftoken_52',['current_token',['../classbdd__demo__python_1_1_expression_parser.html#ac281fd14a66ade48d97e6f29abee6901',1,'bdd_demo_python::ExpressionParser']]],
  ['cve_20monitoring_53',['CVE Monitoring',['../md_documentation_2dependency-management.html#autotoc_md48',1,'']]]
];
